CREATE TABLE transfer
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    accountFrom  VARCHAR(255),
    accountTo    VARCHAR(255),
    transferDate TIMESTAMP WITHOUT TIME ZONE,
    amount       DECIMAL,
    CONSTRAINT pk_transfer PRIMARY KEY (id)
);